<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_menu_attack_player</name>
   <tag></tag>
   <elementGuidId>516287ca-ef92-4ac8-8e04-f4255f6fcc3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-:rj:']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @title = 'Attack Player' and (text() = 'Attack Player' or . = 'Attack Player')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f20775d-3282-4cee-a407-9ddf8fed63f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d464a85-58ee-4967-a90a-202f4eef06e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:rk:</value>
      <webElementGuid>838f003d-0305-4e7c-b464-2e3d5cfc7a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d949c01-ffd4-423a-8a78-4e4614449261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>dd5fa281-43a8-469f-b397-46d2f9f23446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>b8c83fa9-162b-49d1-9a65-63902bb3c9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:rj:</value>
      <webElementGuid>a83dd611-931e-4ad5-9233-25c69b3f90ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-1 items-center justify-between font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180 p-2 max-w-full rounded-lg border-border data-[state=closed]:border-b data-[state=closed]:bg-background</value>
      <webElementGuid>f6d47836-32a1-446f-8e22-5efdb30e2c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Attack Player</value>
      <webElementGuid>a57d63c3-25c4-4be1-af0d-4ae443490756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attack Player</value>
      <webElementGuid>7f01d854-c5a7-48f1-a5c5-48f20f2a3e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='radix-:rj:']</value>
      <webElementGuid>702c784d-5c7c-4b20-ba59-ce254da8d9cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='radix-:rj:']</value>
      <webElementGuid>7319701a-9cd8-425d-867b-979c510e7505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2:']/div/div/div[2]/h3/button</value>
      <webElementGuid>3b25f117-f640-4751-b12b-11f7fc08d633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nickname'])[1]/following::button[1]</value>
      <webElementGuid>0b97db8e-3ee2-4a85-b867-ed5dfbeec16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/following::button[3]</value>
      <webElementGuid>cf6ab6df-e498-4c25-bbc3-2a1bacaf5198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='target'])[1]/preceding::button[1]</value>
      <webElementGuid>7d8d8836-aab6-497b-a65a-30ceb381dca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='direction, target'])[1]/preceding::button[2]</value>
      <webElementGuid>1bda8e4c-4745-4a7e-b503-48546806b431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h3/button</value>
      <webElementGuid>fc347645-66e2-4ef6-a8e8-ff39bbfa3285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-:rj:' and @title = 'Attack Player' and (text() = 'Attack Player' or . = 'Attack Player')]</value>
      <webElementGuid>e7214ecb-46d2-4fac-b5f1-c5ea9abbbb25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
