<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>entity_position_player_section</name>
   <tag></tag>
   <elementGuidId>0d15bbae-ca99-47df-95b6-14b168c2d0bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div/div/div/div[2]/div[2]/div[2]/div[10]/div[2]/details[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>44ff0671-2605-4c0d-b02c-6c7dc8971abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X: 0Y: 1</value>
      <webElementGuid>0ad50c39-fcf1-4c58-9d4e-531b5d155ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;flex h-[calc(100%-3rem-1px)]&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex h-full w-full data-[panel-group-direction=vertical]:flex-col&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;bg-muted h-full px-4 pt-4 pb-16 overflow-y-auto&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;space-y-4&quot;]/div[@class=&quot;grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 3xl:flex 3xl:flex-wrap&quot;]/div[@class=&quot;3xl:min-w-96 bg-background border border-border rounded-lg font-mono text-sm&quot;]/div[@class=&quot;px-3 py-2 space-y-2&quot;]/details[@class=&quot;space-y-1 text-[0.8125rem]&quot;]/div[1]</value>
      <webElementGuid>3a9f24c9-b171-4098-a730-956dcbd78002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div/div/div/div[2]/div[2]/div[2]/div[10]/div[2]/details[3]/div</value>
      <webElementGuid>83c2c253-748e-467d-a7fd-634ed38f87a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='{} 2 keys'])[10]/following::div[1]</value>
      <webElementGuid>59931a35-3f38-41ca-9482-8906b4890fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/details[3]/div</value>
      <webElementGuid>249052fd-bcb7-4139-b099-223ebc0a5c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'X: 0Y: 1' or . = 'X: 0Y: 1')]</value>
      <webElementGuid>82c3f6fd-dbbf-4522-bbce-5734404be743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
